# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_frame.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='video_frame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11video_frame.proto\"\xaa\x01\n\nVideoFrame\x12\x14\n\x0c\x66rame_number\x18\x01 \x01(\x04\x12\x13\n\x0b\x66rame_width\x18\x02 \x01(\x05\x12\x14\n\x0c\x66rame_height\x18\x03 \x01(\x05\x12\x16\n\x0e\x66rame_channels\x18\x04 \x01(\x05\x12\x16\n\x0e\x66rame_raw_data\x18\x05 \x01(\x0c\x12\x17\n\x0f\x66rame_bgr_color\x18\x06 \x01(\x08\x12\x12\n\npublish_by\x18\x07 \x01(\tb\x06proto3')
)




_VIDEOFRAME = _descriptor.Descriptor(
  name='VideoFrame',
  full_name='VideoFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_number', full_name='VideoFrame.frame_number', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_width', full_name='VideoFrame.frame_width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_height', full_name='VideoFrame.frame_height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_channels', full_name='VideoFrame.frame_channels', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_raw_data', full_name='VideoFrame.frame_raw_data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_bgr_color', full_name='VideoFrame.frame_bgr_color', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_by', full_name='VideoFrame.publish_by', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=192,
)

DESCRIPTOR.message_types_by_name['VideoFrame'] = _VIDEOFRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFrame = _reflection.GeneratedProtocolMessageType('VideoFrame', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOFRAME,
  __module__ = 'video_frame_pb2'
  # @@protoc_insertion_point(class_scope:VideoFrame)
  ))
_sym_db.RegisterMessage(VideoFrame)


# @@protoc_insertion_point(module_scope)
