// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_frame.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_video_5fframe_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_video_5fframe_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_video_5fframe_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_video_5fframe_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_video_5fframe_2eproto;
class VideoFrame;
class VideoFrameDefaultTypeInternal;
extern VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::VideoFrame* Arena::CreateMaybeMessage<::VideoFrame>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class VideoFrame PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VideoFrame) */ {
 public:
  inline VideoFrame() : VideoFrame(nullptr) {};
  virtual ~VideoFrame();

  VideoFrame(const VideoFrame& from);
  VideoFrame(VideoFrame&& from) noexcept
    : VideoFrame() {
    *this = ::std::move(from);
  }

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoFrame& operator=(VideoFrame&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VideoFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VideoFrame* internal_default_instance() {
    return reinterpret_cast<const VideoFrame*>(
               &_VideoFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VideoFrame& a, VideoFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoFrame* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VideoFrame* New() const final {
    return CreateMaybeMessage<VideoFrame>(nullptr);
  }

  VideoFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VideoFrame>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VideoFrame& from);
  void MergeFrom(const VideoFrame& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFrame* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VideoFrame";
  }
  protected:
  explicit VideoFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_video_5fframe_2eproto);
    return ::descriptor_table_video_5fframe_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameRawDataFieldNumber = 5,
    kPublishByFieldNumber = 7,
    kFrameNumberFieldNumber = 1,
    kFrameWidthFieldNumber = 2,
    kFrameHeightFieldNumber = 3,
    kFrameChannelsFieldNumber = 4,
    kFrameFormatFieldNumber = 6,
  };
  // bytes frame_raw_data = 5;
  void clear_frame_raw_data();
  const std::string& frame_raw_data() const;
  void set_frame_raw_data(const std::string& value);
  void set_frame_raw_data(std::string&& value);
  void set_frame_raw_data(const char* value);
  void set_frame_raw_data(const void* value, size_t size);
  std::string* mutable_frame_raw_data();
  std::string* release_frame_raw_data();
  void set_allocated_frame_raw_data(std::string* frame_raw_data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_frame_raw_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_frame_raw_data(
      std::string* frame_raw_data);
  private:
  const std::string& _internal_frame_raw_data() const;
  void _internal_set_frame_raw_data(const std::string& value);
  std::string* _internal_mutable_frame_raw_data();
  public:

  // string publish_by = 7;
  void clear_publish_by();
  const std::string& publish_by() const;
  void set_publish_by(const std::string& value);
  void set_publish_by(std::string&& value);
  void set_publish_by(const char* value);
  void set_publish_by(const char* value, size_t size);
  std::string* mutable_publish_by();
  std::string* release_publish_by();
  void set_allocated_publish_by(std::string* publish_by);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_publish_by();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_publish_by(
      std::string* publish_by);
  private:
  const std::string& _internal_publish_by() const;
  void _internal_set_publish_by(const std::string& value);
  std::string* _internal_mutable_publish_by();
  public:

  // uint64 frame_number = 1;
  void clear_frame_number();
  ::PROTOBUF_NAMESPACE_ID::uint64 frame_number() const;
  void set_frame_number(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_frame_number() const;
  void _internal_set_frame_number(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 frame_width = 2;
  void clear_frame_width();
  ::PROTOBUF_NAMESPACE_ID::int32 frame_width() const;
  void set_frame_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_frame_width() const;
  void _internal_set_frame_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 frame_height = 3;
  void clear_frame_height();
  ::PROTOBUF_NAMESPACE_ID::int32 frame_height() const;
  void set_frame_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_frame_height() const;
  void _internal_set_frame_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 frame_channels = 4;
  void clear_frame_channels();
  ::PROTOBUF_NAMESPACE_ID::int32 frame_channels() const;
  void set_frame_channels(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_frame_channels() const;
  void _internal_set_frame_channels(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 frame_format = 6;
  void clear_frame_format();
  ::PROTOBUF_NAMESPACE_ID::int32 frame_format() const;
  void set_frame_format(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_frame_format() const;
  void _internal_set_frame_format(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:VideoFrame)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_raw_data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr publish_by_;
  ::PROTOBUF_NAMESPACE_ID::uint64 frame_number_;
  ::PROTOBUF_NAMESPACE_ID::int32 frame_width_;
  ::PROTOBUF_NAMESPACE_ID::int32 frame_height_;
  ::PROTOBUF_NAMESPACE_ID::int32 frame_channels_;
  ::PROTOBUF_NAMESPACE_ID::int32 frame_format_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_video_5fframe_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VideoFrame

// uint64 frame_number = 1;
inline void VideoFrame::clear_frame_number() {
  frame_number_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 VideoFrame::_internal_frame_number() const {
  return frame_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 VideoFrame::frame_number() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_number)
  return _internal_frame_number();
}
inline void VideoFrame::_internal_set_frame_number(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  frame_number_ = value;
}
inline void VideoFrame::set_frame_number(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_frame_number(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_number)
}

// int32 frame_width = 2;
inline void VideoFrame::clear_frame_width() {
  frame_width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::_internal_frame_width() const {
  return frame_width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::frame_width() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_width)
  return _internal_frame_width();
}
inline void VideoFrame::_internal_set_frame_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  frame_width_ = value;
}
inline void VideoFrame::set_frame_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_frame_width(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_width)
}

// int32 frame_height = 3;
inline void VideoFrame::clear_frame_height() {
  frame_height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::_internal_frame_height() const {
  return frame_height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::frame_height() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_height)
  return _internal_frame_height();
}
inline void VideoFrame::_internal_set_frame_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  frame_height_ = value;
}
inline void VideoFrame::set_frame_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_frame_height(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_height)
}

// int32 frame_channels = 4;
inline void VideoFrame::clear_frame_channels() {
  frame_channels_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::_internal_frame_channels() const {
  return frame_channels_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::frame_channels() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_channels)
  return _internal_frame_channels();
}
inline void VideoFrame::_internal_set_frame_channels(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  frame_channels_ = value;
}
inline void VideoFrame::set_frame_channels(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_frame_channels(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_channels)
}

// bytes frame_raw_data = 5;
inline void VideoFrame::clear_frame_raw_data() {
  frame_raw_data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& VideoFrame::frame_raw_data() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_raw_data)
  return _internal_frame_raw_data();
}
inline void VideoFrame::set_frame_raw_data(const std::string& value) {
  _internal_set_frame_raw_data(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_raw_data)
}
inline std::string* VideoFrame::mutable_frame_raw_data() {
  // @@protoc_insertion_point(field_mutable:VideoFrame.frame_raw_data)
  return _internal_mutable_frame_raw_data();
}
inline const std::string& VideoFrame::_internal_frame_raw_data() const {
  return frame_raw_data_.Get();
}
inline void VideoFrame::_internal_set_frame_raw_data(const std::string& value) {
  
  frame_raw_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VideoFrame::set_frame_raw_data(std::string&& value) {
  
  frame_raw_data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.frame_raw_data)
}
inline void VideoFrame::set_frame_raw_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  frame_raw_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:VideoFrame.frame_raw_data)
}
inline void VideoFrame::set_frame_raw_data(const void* value,
    size_t size) {
  
  frame_raw_data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.frame_raw_data)
}
inline std::string* VideoFrame::_internal_mutable_frame_raw_data() {
  
  return frame_raw_data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VideoFrame::release_frame_raw_data() {
  // @@protoc_insertion_point(field_release:VideoFrame.frame_raw_data)
  return frame_raw_data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VideoFrame::set_allocated_frame_raw_data(std::string* frame_raw_data) {
  if (frame_raw_data != nullptr) {
    
  } else {
    
  }
  frame_raw_data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_raw_data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.frame_raw_data)
}
inline std::string* VideoFrame::unsafe_arena_release_frame_raw_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:VideoFrame.frame_raw_data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return frame_raw_data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VideoFrame::unsafe_arena_set_allocated_frame_raw_data(
    std::string* frame_raw_data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (frame_raw_data != nullptr) {
    
  } else {
    
  }
  frame_raw_data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      frame_raw_data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:VideoFrame.frame_raw_data)
}

// int32 frame_format = 6;
inline void VideoFrame::clear_frame_format() {
  frame_format_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::_internal_frame_format() const {
  return frame_format_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 VideoFrame::frame_format() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_format)
  return _internal_frame_format();
}
inline void VideoFrame::_internal_set_frame_format(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  frame_format_ = value;
}
inline void VideoFrame::set_frame_format(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_frame_format(value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_format)
}

// string publish_by = 7;
inline void VideoFrame::clear_publish_by() {
  publish_by_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& VideoFrame::publish_by() const {
  // @@protoc_insertion_point(field_get:VideoFrame.publish_by)
  return _internal_publish_by();
}
inline void VideoFrame::set_publish_by(const std::string& value) {
  _internal_set_publish_by(value);
  // @@protoc_insertion_point(field_set:VideoFrame.publish_by)
}
inline std::string* VideoFrame::mutable_publish_by() {
  // @@protoc_insertion_point(field_mutable:VideoFrame.publish_by)
  return _internal_mutable_publish_by();
}
inline const std::string& VideoFrame::_internal_publish_by() const {
  return publish_by_.Get();
}
inline void VideoFrame::_internal_set_publish_by(const std::string& value) {
  
  publish_by_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void VideoFrame::set_publish_by(std::string&& value) {
  
  publish_by_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.publish_by)
}
inline void VideoFrame::set_publish_by(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  publish_by_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:VideoFrame.publish_by)
}
inline void VideoFrame::set_publish_by(const char* value,
    size_t size) {
  
  publish_by_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.publish_by)
}
inline std::string* VideoFrame::_internal_mutable_publish_by() {
  
  return publish_by_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* VideoFrame::release_publish_by() {
  // @@protoc_insertion_point(field_release:VideoFrame.publish_by)
  return publish_by_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VideoFrame::set_allocated_publish_by(std::string* publish_by) {
  if (publish_by != nullptr) {
    
  } else {
    
  }
  publish_by_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), publish_by,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.publish_by)
}
inline std::string* VideoFrame::unsafe_arena_release_publish_by() {
  // @@protoc_insertion_point(field_unsafe_arena_release:VideoFrame.publish_by)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return publish_by_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void VideoFrame::unsafe_arena_set_allocated_publish_by(
    std::string* publish_by) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (publish_by != nullptr) {
    
  } else {
    
  }
  publish_by_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      publish_by, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:VideoFrame.publish_by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_video_5fframe_2eproto
