// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_frame.proto

#ifndef PROTOBUF_INCLUDED_video_5fframe_2eproto
#define PROTOBUF_INCLUDED_video_5fframe_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_video_5fframe_2eproto 

namespace protobuf_video_5fframe_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_video_5fframe_2eproto
class VideoFrame;
class VideoFrameDefaultTypeInternal;
extern VideoFrameDefaultTypeInternal _VideoFrame_default_instance_;
namespace google {
namespace protobuf {
template<> ::VideoFrame* Arena::CreateMaybeMessage<::VideoFrame>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class VideoFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:VideoFrame) */ {
 public:
  VideoFrame();
  virtual ~VideoFrame();

  VideoFrame(const VideoFrame& from);

  inline VideoFrame& operator=(const VideoFrame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VideoFrame(VideoFrame&& from) noexcept
    : VideoFrame() {
    *this = ::std::move(from);
  }

  inline VideoFrame& operator=(VideoFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const VideoFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VideoFrame* internal_default_instance() {
    return reinterpret_cast<const VideoFrame*>(
               &_VideoFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(VideoFrame* other);
  friend void swap(VideoFrame& a, VideoFrame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VideoFrame* New() const final {
    return CreateMaybeMessage<VideoFrame>(NULL);
  }

  VideoFrame* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<VideoFrame>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const VideoFrame& from);
  void MergeFrom(const VideoFrame& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes frame_raw_data = 5;
  void clear_frame_raw_data();
  static const int kFrameRawDataFieldNumber = 5;
  const ::std::string& frame_raw_data() const;
  void set_frame_raw_data(const ::std::string& value);
  #if LANG_CXX11
  void set_frame_raw_data(::std::string&& value);
  #endif
  void set_frame_raw_data(const char* value);
  void set_frame_raw_data(const void* value, size_t size);
  ::std::string* mutable_frame_raw_data();
  ::std::string* release_frame_raw_data();
  void set_allocated_frame_raw_data(::std::string* frame_raw_data);

  // string publish_by = 7;
  void clear_publish_by();
  static const int kPublishByFieldNumber = 7;
  const ::std::string& publish_by() const;
  void set_publish_by(const ::std::string& value);
  #if LANG_CXX11
  void set_publish_by(::std::string&& value);
  #endif
  void set_publish_by(const char* value);
  void set_publish_by(const char* value, size_t size);
  ::std::string* mutable_publish_by();
  ::std::string* release_publish_by();
  void set_allocated_publish_by(::std::string* publish_by);

  // uint64 frame_number = 1;
  void clear_frame_number();
  static const int kFrameNumberFieldNumber = 1;
  ::google::protobuf::uint64 frame_number() const;
  void set_frame_number(::google::protobuf::uint64 value);

  // int32 frame_width = 2;
  void clear_frame_width();
  static const int kFrameWidthFieldNumber = 2;
  ::google::protobuf::int32 frame_width() const;
  void set_frame_width(::google::protobuf::int32 value);

  // int32 frame_height = 3;
  void clear_frame_height();
  static const int kFrameHeightFieldNumber = 3;
  ::google::protobuf::int32 frame_height() const;
  void set_frame_height(::google::protobuf::int32 value);

  // int32 frame_channels = 4;
  void clear_frame_channels();
  static const int kFrameChannelsFieldNumber = 4;
  ::google::protobuf::int32 frame_channels() const;
  void set_frame_channels(::google::protobuf::int32 value);

  // bool frame_bgr_color = 6;
  void clear_frame_bgr_color();
  static const int kFrameBgrColorFieldNumber = 6;
  bool frame_bgr_color() const;
  void set_frame_bgr_color(bool value);

  // @@protoc_insertion_point(class_scope:VideoFrame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr frame_raw_data_;
  ::google::protobuf::internal::ArenaStringPtr publish_by_;
  ::google::protobuf::uint64 frame_number_;
  ::google::protobuf::int32 frame_width_;
  ::google::protobuf::int32 frame_height_;
  ::google::protobuf::int32 frame_channels_;
  bool frame_bgr_color_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_video_5fframe_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VideoFrame

// uint64 frame_number = 1;
inline void VideoFrame::clear_frame_number() {
  frame_number_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 VideoFrame::frame_number() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_number)
  return frame_number_;
}
inline void VideoFrame::set_frame_number(::google::protobuf::uint64 value) {
  
  frame_number_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.frame_number)
}

// int32 frame_width = 2;
inline void VideoFrame::clear_frame_width() {
  frame_width_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::frame_width() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_width)
  return frame_width_;
}
inline void VideoFrame::set_frame_width(::google::protobuf::int32 value) {
  
  frame_width_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.frame_width)
}

// int32 frame_height = 3;
inline void VideoFrame::clear_frame_height() {
  frame_height_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::frame_height() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_height)
  return frame_height_;
}
inline void VideoFrame::set_frame_height(::google::protobuf::int32 value) {
  
  frame_height_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.frame_height)
}

// int32 frame_channels = 4;
inline void VideoFrame::clear_frame_channels() {
  frame_channels_ = 0;
}
inline ::google::protobuf::int32 VideoFrame::frame_channels() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_channels)
  return frame_channels_;
}
inline void VideoFrame::set_frame_channels(::google::protobuf::int32 value) {
  
  frame_channels_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.frame_channels)
}

// bytes frame_raw_data = 5;
inline void VideoFrame::clear_frame_raw_data() {
  frame_raw_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VideoFrame::frame_raw_data() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_raw_data)
  return frame_raw_data_.GetNoArena();
}
inline void VideoFrame::set_frame_raw_data(const ::std::string& value) {
  
  frame_raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFrame.frame_raw_data)
}
#if LANG_CXX11
inline void VideoFrame::set_frame_raw_data(::std::string&& value) {
  
  frame_raw_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.frame_raw_data)
}
#endif
inline void VideoFrame::set_frame_raw_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  frame_raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFrame.frame_raw_data)
}
inline void VideoFrame::set_frame_raw_data(const void* value, size_t size) {
  
  frame_raw_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.frame_raw_data)
}
inline ::std::string* VideoFrame::mutable_frame_raw_data() {
  
  // @@protoc_insertion_point(field_mutable:VideoFrame.frame_raw_data)
  return frame_raw_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_frame_raw_data() {
  // @@protoc_insertion_point(field_release:VideoFrame.frame_raw_data)
  
  return frame_raw_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFrame::set_allocated_frame_raw_data(::std::string* frame_raw_data) {
  if (frame_raw_data != NULL) {
    
  } else {
    
  }
  frame_raw_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), frame_raw_data);
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.frame_raw_data)
}

// bool frame_bgr_color = 6;
inline void VideoFrame::clear_frame_bgr_color() {
  frame_bgr_color_ = false;
}
inline bool VideoFrame::frame_bgr_color() const {
  // @@protoc_insertion_point(field_get:VideoFrame.frame_bgr_color)
  return frame_bgr_color_;
}
inline void VideoFrame::set_frame_bgr_color(bool value) {
  
  frame_bgr_color_ = value;
  // @@protoc_insertion_point(field_set:VideoFrame.frame_bgr_color)
}

// string publish_by = 7;
inline void VideoFrame::clear_publish_by() {
  publish_by_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& VideoFrame::publish_by() const {
  // @@protoc_insertion_point(field_get:VideoFrame.publish_by)
  return publish_by_.GetNoArena();
}
inline void VideoFrame::set_publish_by(const ::std::string& value) {
  
  publish_by_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:VideoFrame.publish_by)
}
#if LANG_CXX11
inline void VideoFrame::set_publish_by(::std::string&& value) {
  
  publish_by_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:VideoFrame.publish_by)
}
#endif
inline void VideoFrame::set_publish_by(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  publish_by_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:VideoFrame.publish_by)
}
inline void VideoFrame::set_publish_by(const char* value, size_t size) {
  
  publish_by_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:VideoFrame.publish_by)
}
inline ::std::string* VideoFrame::mutable_publish_by() {
  
  // @@protoc_insertion_point(field_mutable:VideoFrame.publish_by)
  return publish_by_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* VideoFrame::release_publish_by() {
  // @@protoc_insertion_point(field_release:VideoFrame.publish_by)
  
  return publish_by_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void VideoFrame::set_allocated_publish_by(::std::string* publish_by) {
  if (publish_by != NULL) {
    
  } else {
    
  }
  publish_by_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), publish_by);
  // @@protoc_insertion_point(field_set_allocated:VideoFrame.publish_by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_video_5fframe_2eproto
