// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video_frame.proto

#include "video_frame.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class VideoFrameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VideoFrame>
      _instance;
} _VideoFrame_default_instance_;
namespace protobuf_video_5fframe_2eproto {
static void InitDefaultsVideoFrame() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_VideoFrame_default_instance_;
    new (ptr) ::VideoFrame();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::VideoFrame::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VideoFrame =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVideoFrame}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_VideoFrame.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_width_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_height_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_channels_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_raw_data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, frame_bgr_color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::VideoFrame, publish_by_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::VideoFrame)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_VideoFrame_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "video_frame.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021video_frame.proto\"\252\001\n\nVideoFrame\022\024\n\014fr"
      "ame_number\030\001 \001(\004\022\023\n\013frame_width\030\002 \001(\005\022\024\n"
      "\014frame_height\030\003 \001(\005\022\026\n\016frame_channels\030\004 "
      "\001(\005\022\026\n\016frame_raw_data\030\005 \001(\014\022\027\n\017frame_bgr"
      "_color\030\006 \001(\010\022\022\n\npublish_by\030\007 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 200);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "video_frame.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_video_5fframe_2eproto

// ===================================================================

void VideoFrame::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VideoFrame::kFrameNumberFieldNumber;
const int VideoFrame::kFrameWidthFieldNumber;
const int VideoFrame::kFrameHeightFieldNumber;
const int VideoFrame::kFrameChannelsFieldNumber;
const int VideoFrame::kFrameRawDataFieldNumber;
const int VideoFrame::kFrameBgrColorFieldNumber;
const int VideoFrame::kPublishByFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VideoFrame::VideoFrame()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_video_5fframe_2eproto::scc_info_VideoFrame.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:VideoFrame)
}
VideoFrame::VideoFrame(const VideoFrame& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  frame_raw_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.frame_raw_data().size() > 0) {
    frame_raw_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_raw_data_);
  }
  publish_by_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.publish_by().size() > 0) {
    publish_by_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.publish_by_);
  }
  ::memcpy(&frame_number_, &from.frame_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&frame_bgr_color_) -
    reinterpret_cast<char*>(&frame_number_)) + sizeof(frame_bgr_color_));
  // @@protoc_insertion_point(copy_constructor:VideoFrame)
}

void VideoFrame::SharedCtor() {
  frame_raw_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  publish_by_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&frame_bgr_color_) -
      reinterpret_cast<char*>(&frame_number_)) + sizeof(frame_bgr_color_));
}

VideoFrame::~VideoFrame() {
  // @@protoc_insertion_point(destructor:VideoFrame)
  SharedDtor();
}

void VideoFrame::SharedDtor() {
  frame_raw_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  publish_by_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void VideoFrame::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VideoFrame::descriptor() {
  ::protobuf_video_5fframe_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_video_5fframe_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VideoFrame& VideoFrame::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_video_5fframe_2eproto::scc_info_VideoFrame.base);
  return *internal_default_instance();
}


void VideoFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  frame_raw_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  publish_by_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&frame_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&frame_bgr_color_) -
      reinterpret_cast<char*>(&frame_number_)) + sizeof(frame_bgr_color_));
  _internal_metadata_.Clear();
}

bool VideoFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:VideoFrame)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 frame_number = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &frame_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 frame_width = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_width_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 frame_height = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 frame_channels = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_channels_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes frame_raw_data = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_frame_raw_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool frame_bgr_color = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &frame_bgr_color_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string publish_by = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_publish_by()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->publish_by().data(), static_cast<int>(this->publish_by().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "VideoFrame.publish_by"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:VideoFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:VideoFrame)
  return false;
#undef DO_
}

void VideoFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_number = 1;
  if (this->frame_number() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->frame_number(), output);
  }

  // int32 frame_width = 2;
  if (this->frame_width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->frame_width(), output);
  }

  // int32 frame_height = 3;
  if (this->frame_height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->frame_height(), output);
  }

  // int32 frame_channels = 4;
  if (this->frame_channels() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->frame_channels(), output);
  }

  // bytes frame_raw_data = 5;
  if (this->frame_raw_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->frame_raw_data(), output);
  }

  // bool frame_bgr_color = 6;
  if (this->frame_bgr_color() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->frame_bgr_color(), output);
  }

  // string publish_by = 7;
  if (this->publish_by().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->publish_by().data(), static_cast<int>(this->publish_by().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "VideoFrame.publish_by");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->publish_by(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:VideoFrame)
}

::google::protobuf::uint8* VideoFrame::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:VideoFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 frame_number = 1;
  if (this->frame_number() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->frame_number(), target);
  }

  // int32 frame_width = 2;
  if (this->frame_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->frame_width(), target);
  }

  // int32 frame_height = 3;
  if (this->frame_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->frame_height(), target);
  }

  // int32 frame_channels = 4;
  if (this->frame_channels() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->frame_channels(), target);
  }

  // bytes frame_raw_data = 5;
  if (this->frame_raw_data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->frame_raw_data(), target);
  }

  // bool frame_bgr_color = 6;
  if (this->frame_bgr_color() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->frame_bgr_color(), target);
  }

  // string publish_by = 7;
  if (this->publish_by().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->publish_by().data(), static_cast<int>(this->publish_by().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "VideoFrame.publish_by");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->publish_by(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VideoFrame)
  return target;
}

size_t VideoFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VideoFrame)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes frame_raw_data = 5;
  if (this->frame_raw_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->frame_raw_data());
  }

  // string publish_by = 7;
  if (this->publish_by().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->publish_by());
  }

  // uint64 frame_number = 1;
  if (this->frame_number() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->frame_number());
  }

  // int32 frame_width = 2;
  if (this->frame_width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->frame_width());
  }

  // int32 frame_height = 3;
  if (this->frame_height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->frame_height());
  }

  // int32 frame_channels = 4;
  if (this->frame_channels() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->frame_channels());
  }

  // bool frame_bgr_color = 6;
  if (this->frame_bgr_color() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VideoFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VideoFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const VideoFrame* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VideoFrame>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VideoFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VideoFrame)
    MergeFrom(*source);
  }
}

void VideoFrame::MergeFrom(const VideoFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VideoFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.frame_raw_data().size() > 0) {

    frame_raw_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.frame_raw_data_);
  }
  if (from.publish_by().size() > 0) {

    publish_by_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.publish_by_);
  }
  if (from.frame_number() != 0) {
    set_frame_number(from.frame_number());
  }
  if (from.frame_width() != 0) {
    set_frame_width(from.frame_width());
  }
  if (from.frame_height() != 0) {
    set_frame_height(from.frame_height());
  }
  if (from.frame_channels() != 0) {
    set_frame_channels(from.frame_channels());
  }
  if (from.frame_bgr_color() != 0) {
    set_frame_bgr_color(from.frame_bgr_color());
  }
}

void VideoFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VideoFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VideoFrame::CopyFrom(const VideoFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VideoFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VideoFrame::IsInitialized() const {
  return true;
}

void VideoFrame::Swap(VideoFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VideoFrame::InternalSwap(VideoFrame* other) {
  using std::swap;
  frame_raw_data_.Swap(&other->frame_raw_data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  publish_by_.Swap(&other->publish_by_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(frame_number_, other->frame_number_);
  swap(frame_width_, other->frame_width_);
  swap(frame_height_, other->frame_height_);
  swap(frame_channels_, other->frame_channels_);
  swap(frame_bgr_color_, other->frame_bgr_color_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VideoFrame::GetMetadata() const {
  protobuf_video_5fframe_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_video_5fframe_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::VideoFrame* Arena::CreateMaybeMessage< ::VideoFrame >(Arena* arena) {
  return Arena::CreateInternal< ::VideoFrame >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
